name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        platform: [Win32, x64]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -A ${{matrix.platform}}

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}} 
